id = 2
kind = "bug"
title = "Cannot go back after entering username, stuck on password"
description = ""
author = "Thomas Mathews <thomas.mathews@kleientertainment.com>"
state = "open"
created_at = "2026-08-30T12:13:08.874747201Z"
updated_at = "2026-08-30T12:13:08.890847452Z"
